### ISSUE TITLE
List of opened issues waiting for new releases

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#1105]
- #1010 **GCP connectors GCS (Source and Sink) and Spanner** are failing license check with JDK8 (internal issue [CCMSG-1139](https://confluentinc.atlassian.net/browse/CCMSG-1139))
- #935 Allow **S3 sink** to use assume role with aws.access.key.id (internal issue [CC-14617](https://confluentinc.atlassian.net/browse/CC-14617))
- #921 Add AssumeRole Credentials Provider to **S3 Source** connector (internal issue [CCMSG-1015](https://confluentinc.atlassian.net/browse/CCMSG-1015))
- #778 **Azure Blob Storage Source** 1.4.6 not working with CP 6.1.2 and CP 6.2.0 (internal issue [CCMSG-1192](https://confluentinc.atlassian.net/browse/CCMSG-1192))
- #1168 **HDFS2 Source** error Failed to specify server's Kerberos principal name (internal issue [CCMSG-1224](https://confluentinc.atlassian.net/browse/CCMSG-1224))
- #1175 **HDFS3 Source** error Failed to specify server's Kerberos principal name (internal issue [CCMSG-1231](https://confluentinc.atlassian.net/browse/CCMSG-1231))
- #1231 and #1230 **Azure Cosmosdb Source and Sink** Failed to find any class that implements Connector when using JDK 1.8 (Microsoft issue [#413](https://github.com/microsoft/kafka-connect-cosmosdb/issues/413))

**Comment by vdesabou** [comment]
DONE:

- [ ] #1146 **Azure Search Sink** fails to start with NoClassDefFoundError: org/codehaus/jackson/node/ValueNode since 1.0.2 (internal issue [CC-15143](https://confluentinc.atlassian.net/browse/CC-15143))
