### ISSUE TITLE
Playground : List of opened issues

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/kafka-docker-playground#2168]
- [#935](https://github.com/vdesabou/kafka-docker-playground/issues/935) Allow **S3 sink** to use assume role with aws.access.key.id (internal issue [CC-14617](https://confluentinc.atlassian.net/browse/CC-14617))
- [#921](https://github.com/vdesabou/kafka-docker-playground/issues/921) Add AssumeRole Credentials Provider to **S3 Source** connector (internal issue [CCMSG-1015](https://confluentinc.atlassian.net/browse/CCMSG-1015))
- [#1168](https://github.com/vdesabou/kafka-docker-playground/issues/1168) **HDFS2 Source** error Failed to specify server's Kerberos principal name (internal issue [CCMSG-1224](https://confluentinc.atlassian.net/browse/CCMSG-1224))
- [#1175](https://github.com/vdesabou/kafka-docker-playground/issues/1175) **HDFS3 Source** error Failed to specify server's Kerberos principal name (internal issue [CCMSG-1231](https://confluentinc.atlassian.net/browse/CCMSG-1231))
- [#1416](https://github.com/vdesabou/kafka-docker-playground/issues/935) confluentinc/kafka-connect-replicator 5.4.5 is failing license check with JDK8 (internal issue [REPL-1845](https://confluentinc.atlassian.net/browse/REPL-1845))
- [#1690](https://github.com/vdesabou/kafka-docker-playground/issues/1690) GCP Spanner Sink: proxy is not working (internal issue [CCDB-4440](https://confluentinc.atlassian.net/browse/CCDB-4440))
- [#1509](https://github.com/vdesabou/kafka-docker-playground/issues/1509) Syslog source: NoClassDefFoundError for io/netty/handler/ssl/SslContext with CP 5.3.6 (internal issue [CC-16215](https://confluentinc.atlassian.net/browse/CC-16215))
-  [#2087](https://github.com/vdesabou/kafka-docker-playground/issues/2087) HBASE sink connector 2.x: NoClassDefFoundError: Could not initialize class sun.misc.Unsafe (internal issue [CCDB-4517](https://confluentinc.atlassian.net/browse/CCDB-4517))

**Comment by vdesabou** [comment]
DONE:

- [x] #1146 **Azure Search Sink** fails to start with NoClassDefFoundError: org/codehaus/jackson/node/ValueNode since 1.0.2 (internal issue [CC-15143](https://confluentinc.atlassian.net/browse/CC-15143))
- [x] #931 az functionapp create fails when using Docker az cli (Microsoft issue [#17948](https://github.com/Azure/azure-cli/issues/17948))
- [x] #1010 **GCP connectors GCS (Source and Sink) and Spanner** are failing license check with JDK8 (internal issue [CCMSG-1139](https://confluentinc.atlassian.net/browse/CCMSG-1139))
- [x] #1371 **Filepulse source** (Filepulse issue https://github.com/streamthoughts/kafka-connect-file-pulse/issues/182)
- [x] #778 **Azure Blob Storage Source** 1.4.6 not working with CP 6.1.2 and CP 6.2.0 (internal issue [CCMSG-1192](https://confluentinc.atlassian.net/browse/CCMSG-1192))
- [x]  #1727 and #1421 cp-enterprise-replicator-executable regression with 5.4.5 (internal issue [REPL-1844](https://confluentinc.atlassian.net/browse/REPL-1844) and PR https://github.com/confluentinc/kafka-replicator-images/pull/44)
- [x] #1549 Neo4j sink: NoClassDefFoundError for com/google/common/base/Preconditions with CP 5.3.6 (internal issue [CCDB-4431](https://confluentinc.atlassian.net/browse/CCDB-4431) but would required to be fixed in connector ? Opened https://github.com/neo4j-contrib/neo4j-streams/issues/510)
- [x] #1425 (internal issue [ST-6539](https://confluentinc.atlassian.net/browse/ST-6539)) 🚨 a workaround is implemented, see #1644.  ---> it works starting from 5.3.7
- [x] #1715 and #1717 SalesForce CDC Source and PushTopics Source: Unknown configuration 'http.proxy.auth.scheme' (internal issue [CCLOG-1225](https://confluentinc.atlassian.net/browse/CCLOG-1225))
- [x] #1899 Snowflake Connector Sink no more working since 1.6.3: opened [snowflake issue](https://github.com/snowflakedb/snowflake-kafka-connector/issues/369) 
- [x] [#1568](https://github.com/vdesabou/kafka-docker-playground/issues/1568)GCP BigQuery sink: NoClassDefFoundError org/apache/kafka/common/config/ConfigDef$CaseInsensitiveValidString with CP 5.3.6 (internal issue [CCDB-4437](https://confluentinc.atlassian.net/browse/CCDB-4437))
- [ ] [#1527](https://github.com/vdesabou/kafka-docker-playground/issues/1527) HDFS3 sink: NoClassDefFoundError com/google/common/collect/ImmutableMap with CP 5.3.6 (internal issue [CCMSG-1476](https://confluentinc.atlassian.net/browse/CCMSG-1476))
- [x] [#1896](https://github.com/vdesabou/kafka-docker-playground/issues/1896) [#1894](https://github.com/vdesabou/kafka-docker-playground/issues/1894) [#1168](https://github.com/vdesabou/kafka-docker-playground/issues/1168) [#1175](https://github.com/vdesabou/kafka-docker-playground/issues/1175) and [#921](https://github.com/vdesabou/kafka-docker-playground/issues/921)21 Azure Blob Storage, S3, HDFS 2, HDFS 3 and GCS Source connector >= 2.0.0 not working with CP < 6.x (internal issue [CCMSG-1564](https://confluentinc.atlassian.net/browse/CCMSG-1564))

SKIPPED:

- [x] #1397 and #1396 **Azure Cosmosdb Source and Sink** Failed to find any class that implements Connector when using JDK 1.8 (Microsoft issue [#413](https://github.com/microsoft/kafka-connect-cosmosdb/issues/413))

ENHANCEMENT:

- [x] - [#2101](https://github.com/vdesabou/kafka-docker-playground/issues/2101) SalesForce CDC Source and PushTopics Source: Unknown configuration 'http.proxy.user"' (internal issue [RCCA-5517](https://confluentinc.atlassian.net/browse/RCCA-5517))
